#!/bin/bash

source /infra/utils

set -e
set -u
set -x

cd $TARGET
DIR=$(setup_dir)

export DJANGO_SETTINGS_MODULE=omeroweb.settings
export OMERODIR=/opt/omero/web/OMERO.web
export ICE_CONFIG=${OMERO_DIST}/etc/ice.config

if [ -e test ]; then
   echo Tests currently disabled
   exit 1
fi
